name: Gradle CI

on: [workflow_dispatch, push, pull_request]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  call-workflow:
    uses: tomasbjerre/.github/.github/workflows/gradle-ci.yaml@master
    secrets: inherit
